#dev.off()
#rm(list=ls())
library(ggplot2)
library(tidyr)
library(gridExtra)
library(ggthemes)
library(qqman)
library(dplyr)

Data <- read.table("FSTscan_GATK_20vs20_5kb2.5_IT.windowed.weir.fst", header = T) #the same was performed for the SA lineage contrast (input file FSTscan_GATK_10vs10_5kb2.5_SA.windowed.weir.fst)
colnames(Data) <- c("CHROM","BP","end","nSNPs","FST","MEAN_FST")
Data$FST[Data$FST<0] <- 0
Data$Loc <- Data$CHROM
Data$CHROM <- gsub("CM014743.1\\b", "Chr_1", Data$CHROM)
Data$CHROM <- gsub("CM014744.1\\b", "Chr_2", Data$CHROM)
Data$CHROM <- gsub("CM014745.1\\b", "Chr_3", Data$CHROM)
Data$CHROM <- gsub("CM014746.1\\b", "Chr_4", Data$CHROM)
Data$CHROM <- gsub("CM014747.1\\b", "Chr_5", Data$CHROM)
Data$CHROM <- gsub("CM014748.1\\b", "Chr_6", Data$CHROM)
Data$CHROM <- gsub("CM014749.1\\b", "Chr_7", Data$CHROM)
Data$CHROM <- gsub("CM014750.1\\b", "Chr_8", Data$CHROM)
Data$CHROM <- gsub("CM014751.1\\b", "Chr_9", Data$CHROM)
Data$CHROM <- gsub("CM014752.1\\b", "Chr_10", Data$CHROM)
Data$CHROM <- gsub("CM014753.1\\b", "Chr_11", Data$CHROM)
Data$CHROM <- gsub("CM014754.1\\b", "Chr_12", Data$CHROM)
Data$CHROM <- gsub("CM014755.1\\b", "Chr_13", Data$CHROM)
Data$CHROM <- gsub("CM014756.1\\b", "Chr_14", Data$CHROM)
Data$CHROM <- gsub("CM014757.1\\b", "Chr_15", Data$CHROM)
Data$CHROM <- gsub("CM014758.1\\b", "Chr_16", Data$CHROM)
Data$CHROM <- gsub("CM014759.1\\b", "Chr_17", Data$CHROM)
Data$CHROM <- gsub("CM014760.1\\b", "Chr_18", Data$CHROM)
Data$CHROM <- gsub("CM014761.1\\b", "Chr_19", Data$CHROM)
Data <- Data[grep("Chr", Data$CHROM), ]
Data$CHROM <- factor(Data$CHROM, levels = c("Chr_1","Chr_2","Chr_3","Chr_4","Chr_5","Chr_6","Chr_7","Chr_8","Chr_9","Chr_10","Chr_11","Chr_12","Chr_13","Chr_14","Chr_15","Chr_16","Chr_17","Chr_18","Chr_19"))
Data$CHROM <- as.numeric(gsub("Chr_", "",Data$CHROM))
Data$SNP <- paste(Data$CHROM,Data$BP,sep="_")
Data$zFst <- Data$FST/sd(Data$FST)
mean(Data$nSNPs)
quantile(Data$zFst, c(0.995), na.rm = T)
Data <- Data %>% mutate(outlier = ifelse(zFst > 5.689177, "outlier", "background"))

Data %>% group_by(outlier) %>% tally()
Data_outlier <- subset(Data, outlier == "outlier")
Data_outlier <- Data_outlier[,c(7,2,3)]
write.table(Data_outlier,"Outliers_IT_5kb2.5_FST.bed", sep = "\t", col.names=F, row.names=F, quote=F)
