#!/bin/bash -l
## The -l above is required to get the full environment with modules.

## Allocation to be charged:
#SBATCH -A naiss2024-22-210

## Job name:
#SBATCH -J merge

## Output name:
## %x = job name, %j = job ID.
## sample_field is replaced by sample's ID by the batch_sub script!
#SBATCH --output=%x_%j_sample_field.out

## Partition:
#SBATCH -p shared

## Requested wall-clock time:
#SBATCH -t 04:00:00

## Number of nodes:
#SBATCH --nodes=1

## Number of MPI processes per node:
#SBATCH --ntasks-per-node=1

## Email me in case time runs out before end of job:
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-user=ivanprates@gmail.com

## Actual commands come below this line.

## The goal of this script is:
## To merge read files for samples with multiple lanes sequenced.

## Focal sample:
sample=sample_field

## Status:
echo "Now merging ${sample}!"

## Change directory:
cd /cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/00_rawdata/${sample}

## If needed, remove previously merged files:
rm ${sample}_merged_*.fq.gz

## Create subdirectory to move the original files into later:
## This will ensure we have only two target sequence files within each main folder.
## (one for forward sequences, one for reverse sequences)
mkdir original_files

## List and store original read files:
file_list=$(ls | grep _L[0-9]_)

## Merge lanes corresponding to forward sequences:
zcat ${sample}_*_1.fq.gz | gzip > ${sample}_merged_1.fq.gz

## Merge lanes corresponding to reverse sequences:
zcat ${sample}_*_2.fq.gz | gzip > ${sample}_merged_2.fq.gz

## Change permissions of files:
chmod 755 ${sample}_merged_*.fq.gz

## Move the original files into the original_files subfolder.
#for file in ${file_list} ; do mv ${file} original_files ; done

## Status:
echo "Merging of ${sample} done!"

## End of script.

