#!/bin/bash -l
## The -l above is required to get the full environment with modules.

## Allocation to be charged:
#SBATCH -A naiss2024-22-210

## Job name:
#SBATCH -J 01

## Output name:
## %x = job name, %j = job ID.
## sample_field is replaced by sample's ID by the batch_sub script!
#SBATCH --output=%j_%x_sample_field.out

## Partition:
#SBATCH -p shared

## Requested wall-clock time:
#SBATCH -t 03:30:00

## Number of nodes:
#SBATCH --nodes=1

## Number of tasks:
#SBATCH --ntasks=1

## Number of CPUs per task and memory per cpu:
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=888M

## Email me in case time runs out before end of job:
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-user=ivanprates@gmail.com

## Actual commands come below this line.

## Modules:
module load fastp/0.20.1
module load fastqc/0.12.1
#module load trimmomatic/0.39

## If needed, specify Trimmomatic's location (module loading has stalled for Trimmomatic):
TRIMMOMATIC_ROOT=/pdc/software/eb/software/trimmomatic/0.39

## Focal sample:
sample=sample_field

## If needed, create destination directories:
#mkdir /cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/00_fastqc
#mkdir /cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/01_trimmed

## Data directory:
datadir=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/00_rawdata/${sample}

## Directory to save fastqc and fastp reports:
fastqcdir=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/00_fastqc

## Save trimmed reads to:
savedir=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/01_trimmed

## Status:
echo "Trimming steps starting for ${sample}!"
date

## Filter poly-G tails inserted by NovaSeq: 
fastp \
--in1 ${datadir}/${sample}_*_1.fq.gz --out1 ${savedir}/${sample}_polyG_1.fq.gz \
--in2 ${datadir}/${sample}_*_2.fq.gz --out2 ${savedir}/${sample}_polyG_2.fq.gz \
--disable_quality_filtering \
--disable_length_filtering \
--disable_adapter_trimming \
--trim_poly_g \
--n_base_limit 50 \
--thread 16 \
-h ${fastqcdir}/${sample}_polyG.html

## Status:
echo "fastp complete for ${sample}!"
date

## Run Trimmomatic:
java -jar $TRIMMOMATIC_ROOT/trimmomatic.jar PE -threads 16 -phred33 \
${savedir}/${sample}_polyG_1.fq.gz \
${savedir}/${sample}_polyG_2.fq.gz \
${savedir}/${sample}_trim_1.fq.gz \
${savedir}/${sample}_trim_unpair1.fq.gz \
${savedir}/${sample}_trim_2.fq.gz \
${savedir}/${sample}_trim_unpair2.fq.gz \
ILLUMINACLIP:$TRIMMOMATIC_ROOT/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:70

# Status:
echo "Trimmomatic complete for ${sample}!"
date

## Change permissions of files:
chmod 755 ${savedir}/${sample}_*.fq.gz

## Run fastqc:
fastqc \
${savedir}/${sample}_trim_1.fq.gz \
${savedir}/${sample}_trim_2.fq.gz \
${savedir}/${sample}_trim_unpair1.fq.gz \
${savedir}/${sample}_trim_unpair2.fq.gz \
-o ${fastqcdir}

## Remove intermediate outputs:
rm ${savedir}/${sample}_polyG_*.fq.gz

# Status:
echo "fastqc complete for ${sample}!"
date

## End of script.

