#!/bin/bash -l
## The -l above is required to get the full environment with modules.

## Allocation to be charged:
#SBATCH -A naiss2024-22-210

## Job name:
#SBATCH -J 2a

## Output name:
## %x = job name, %j = job ID.
## sample_field is replaced by sample's ID by the batch_sub script!
#SBATCH --output=%x_%j_sample_field.out

## Partition:
#SBATCH -p shared

## Requested wall-clock time:
#SBATCH -t 08:15:00

## Number of nodes:
#SBATCH --nodes=1

## Number of tasks:
#SBATCH --ntasks=1

## Number of CPUs per task and memory per cpu:
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=888M

## Email me in case time runs out before end of job:
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-user=ivanprates@gmail.com

## Actual commands come below this line.

## Modules:
module load bwa/0.7.17

## If needed, specify Picard's location (module loading has stalled for Picard):
PICARD_HOME=/pdc/software/eb/software/picard/2.25.5

## Directory with trimmed data:
datadir=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/01_trimmed

## Create destination directory:
mkdir /cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/02_mapped

## Save mapped data to:
savedir=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/02_mapped

## Reference genome to use:

## Podarcis cretensis genome:
#refgenome=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/refgenomes/rPodCre2.1_GCA_951804945.1.fna

## Podarcis gaigeae genome:
#refgenome=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/refgenomes/rPodGai1.hap1.1.primary.fa

## Podarcis pityusensis genome:
#refgenome=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/refgenomes/rPodPit1.hap1.1.primary.fa 

## Podarcis muralis genome (the "Spanish reference"):
refgenome=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/refgenomes/PodMur_1.0_GCF_004329235.1.fna

## Focal sample:
sample=sample_field

## Mapping to the reference genome:
echo "Mapping of ${sample} starting!"
date

bwa mem -M -t 16 ${refgenome} \
${datadir}/${sample}_trim_1.fq.gz ${datadir}/${sample}_trim_2.fq.gz > ${savedir}/${sample}_pair.sam
echo "BWA for ${sample} pair data complete!"

bwa mem -M -t 16 ${refgenome} \
${datadir}/${sample}_trim_unpair1.fq.gz > ${savedir}/${sample}_unpair_1.sam
echo "BWA for ${sample} unpair1 data complete!"

bwa mem -M -t 16 ${refgenome} \
${datadir}/${sample}_trim_unpair2.fq.gz > ${savedir}/${sample}_unpair_2.sam
echo "BWA for ${sample} unpair2 data complete!"

## Status:
echo "BWA mapping of ${sample} completed!"
date

## End of script.

