#!/bin/bash -l
## The -l above is required to get the full environment with modules.

## Allocation to be charged:
#SBATCH -A naiss2024-22-210

## Job name:
#SBATCH -J 2b

## Output name:
## %x = job name, %j = job ID.
## sample_field is replaced by sample's ID by the batch_sub script!
#SBATCH --output=%x_%j_sample_field.out

## Partition:
#SBATCH -p shared

## Requested wall-clock time:
#SBATCH -t 3:00:00

## Number of nodes:
#SBATCH --nodes=1

## Number of tasks:
#SBATCH --ntasks=1

## Number of CPUs per task and memory per cpu:
#SBATCH --cpus-per-task=52
#SBATCH --mem-per-cpu=888M

## Email me in case time runs out before end of job:
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-user=ivanprates@gmail.com

## Actual commands come below this line.

## Modules:
#module load picard/2.25.5

## If needed, specify Picard's location (module loading has stalled for Picard):
PICARD_HOME=/pdc/software/eb/software/picard/2.25.5

## Save mapped data to:
savedir=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/02_mapped

## Focal sample:
sample=sample_field

## Converting sam to bam:
echo "Converting sam to bam for ${sample}!"

java -jar $PICARD_HOME/picard.jar AddOrReplaceReadGroups \
INPUT=${savedir}/${sample}_pair.sam \
OUTPUT=${savedir}/${sample}_pair.bam \
SORT_ORDER=coordinate \
RGLB=${sample}-lib RGPL=ILLUMINA RGPU=${sample}-01 RGSM=${sample}

java -jar $PICARD_HOME/picard.jar AddOrReplaceReadGroups \
INPUT=${savedir}/${sample}_unpair_1.sam \
OUTPUT=${savedir}/${sample}_unpair_1.bam \
SORT_ORDER=coordinate \
RGLB=${sample}-lib RGPL=ILLUMINA RGPU=${sample}-01 RGSM=${sample}

java -jar $PICARD_HOME/picard.jar AddOrReplaceReadGroups \
INPUT=${savedir}/${sample}_unpair_2.sam \
OUTPUT=${savedir}/${sample}_unpair_2.bam \
SORT_ORDER=coordinate \
RGLB=${sample}-lib RGPL=ILLUMINA RGPU=${sample}-01 RGSM=${sample}

## Remove the heavy sam files:
#rm ${savedir}/${sample}_*.sam

## Converting sam to bam:
echo "Conversion of sam to bam for ${sample} completed!"
date

## End of script.

