#!/bin/bash -l
## The -l above is required to get the full environment with modules.

## Allocation to be charged:
#SBATCH -A naiss2024-22-210

## Job name:
#SBATCH -J 2c

## Output name:
## %x = job name, %j = job ID.
## sample_field is replaced by sample's ID by the batch_sub script!
#SBATCH --output=%x_%j_sample_field.out

## Partition:
#SBATCH -p shared

## Requested wall-clock time:
## Most samples finish in 3 hours.
#SBATCH -t 3:00:00

## Number of nodes:
#SBATCH --nodes=1

## Number of tasks:
#SBATCH --ntasks=1

## Number of CPUs per task and memory per CPU:
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=888M

## Email me in case time runs out before end of job:
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-user=ivanprates@gmail.com

## Actual commands come below this line.

## Modules:
#module load picard/2.25.5
module load samtools/1.20

## If needed, specify Picard's location (module loading has stalled for Picard):
PICARD_HOME=/pdc/software/eb/software/picard/2.25.5

## Save mapped data to:
savedir=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/02_mapped

## Focal sample:
sample=sample_field

## Merge bam:
echo "Merging bam for ${sample}!"
date 

java -jar $PICARD_HOME/picard.jar MergeSamFiles \
INPUT=${savedir}/${sample}_pair.bam \
INPUT=${savedir}/${sample}_unpair_1.bam \
INPUT=${savedir}/${sample}_unpair_2.bam \
OUTPUT=${savedir}/${sample}.bam \
SORT_ORDER=coordinate ASSUME_SORTED=true

## Index bam:
echo "Indexing bam for ${sample}!"
date

java -jar $PICARD_HOME/picard.jar BuildBamIndex \
INPUT=${savedir}/${sample}.bam

## Remove intermediate files:
#rm ${savedir}/${sample}_*

## Mapping stats:
samtools flagstat ${savedir}/${sample}.bam > ${savedir}/${sample}_MappingStats.txt

## Mark duplicates:
echo "Marking duplicates for ${sample}!"
date

java -jar $PICARD_HOME/picard.jar MarkDuplicates \
INPUT=${savedir}/${sample}.bam \
OUTPUT=${savedir}/${sample}_marked.bam \
METRICS_FILE=${savedir}/${sample}_marked.metrics

## Index .bam file again:
java -jar $PICARD_HOME/picard.jar BuildBamIndex \
INPUT=${savedir}/${sample}_marked.bam

## Remove intermediate files:
#rm ${savedir}/${sample}.ba*

## Add meaningful IDs:
java -jar $PICARD_HOME/picard.jar AddOrReplaceReadGroups \
INPUT=${savedir}/${sample}_marked.bam \
OUTPUT=${savedir}/${sample}_marked_renamed.bam \
RGID=${sample} RGLB=${sample}-lib \
RGPL=ILLUMINA RGPU=${sample}-01 RGSM=${sample}

## Index again:
java -jar $PICARD_HOME/picard.jar BuildBamIndex \
INPUT=${savedir}/${sample}_marked_renamed.bam

## Remove intermediate files:
#rm ${savedir}/${sample}_marked.ba*

## Status:
echo "Mapping steps of ${sample} completed!"
date

## End of script.

