#!/bin/bash -l
## The -l above is required to get the full environment with modules.

## Allocation to be charged:
#SBATCH -A naiss2024-22-210

## Job name:
#SBATCH -J 03

## Output name:
## %x = job name, %j = job ID.
## time_field, sample_field, and chrom_field are replaced by the batch_sub script!
#SBATCH --output=%j_%x_sample_field_chrom_field.out

## Partition:
#SBATCH -p shared 

## Requested wall-clock time:
#SBATCH -t time_field

## Number of nodes:
#SBATCH --nodes=1

## Number of tasks:
#SBATCH --ntasks=1

## Number of CPUs per task and memory per cpu:
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=888M

## Email me in case time runs out before end of job:
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-user=ivanprates@gmail.com

## Actual commands come below this line.

## Modules:
module load gatk/4.5.0.0

## Directory with mapped data:
datadir=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/02_mapped

## Create destination directory:
mkdir /cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/03_calling

## Save SNP-calling files to:
savedir=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/03_calling

## Reference genome to use:

## Podarcis cretensis genome:
#refgenome=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/refgenomes/rPodCre2.1_GCA_951804945.1.fna

## Podarcis gaigeae genome:
#refgenome=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/refgenomes/rPodGai1.hap1.1.primary.fa

## Podarcis pityusensis genome:
#refgenome=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/refgenomes/rPodPit1.hap1.1.primary.fa

## Podarcis muralis genome (the "Spanish reference"):
refgenome=/cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/refgenomes/PodMur_1.0_GCF_004329235.1.fna

## Focal sample:
sample=sample_field

## Focal chromosome:
chrom=chrom_field

## Status:
echo "SNP calling for ${chrom} of ${sample} is starting!"
date

## Run HaplotypeCaller for focal chromosome and sample:
gatk --java-options "-Xmx13g" HaplotypeCaller \
-R ${refgenome} \
-I ${datadir}/${sample}_marked_renamed.bam \
-L ${chrom} \
-O ${savedir}/${sample}_${chrom}.g.vcf.gz \
-ERC GVCF \
-native-pair-hmm-threads 16

## Status:
echo "SNP calling for ${chrom} of ${sample} completed!"
date
echo "Now indexing q.vcf file!"

## Index g.vcf file that was generated:
gatk IndexFeatureFile -I ${savedir}/${sample}_${chrom}.g.vcf.gz

## Status:
echo "Calling and indexing for ${chrom} of ${sample} completed!"
date

## End of script.

