#!/bin/bash -l
## The -l above is required to get the full environment with modules.

## Allocation to be charged:
#SBATCH -A naiss2025-22-304

## Job name:
#SBATCH -J Depth

## Output name:
## %x = job name, %j = job ID.
#SBATCH --output=%j_%x.out

## Requested wall-clock time:
#SBATCH -t 12:00:00

## Number of nodes:
#SBATCH --nodes=1

## Number of tasks:
#SBATCH --ntasks=1

### Partition:
#SBATCH -p shared

## Number of CPUs per task and memory per cpu:
## The maximum memory per cpu is 888M.
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=888M

## Email me in case time runs out before end of job:
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-user=ivanprates@gmail.com

## Actual commands come below this line.

## Load modules:
module load samtools

## Change folder:
cd /cfs/klemming/projects/snic/naiss2024-23-107/Podarcis/02_mapped

## Loop through all BAM files:
for bam in Pva_*.bam; do
    echo "Now processing $bam"
    sample=$(basename "$bam" .bam)
    avg_cov=$(samtools depth -a "$bam" | awk '{sum+=$3} END {if (NR > 0) print sum/NR; else print 0}')
    echo -e "Sample\tAvg_Coverage\n${sample}\t${avg_cov}" > "coverage_${sample}.txt"
done

## End of script.

